### ISSUE TITLE
New page design implementation for Contributors page

### ISSUE THREAD

**Issue by sudhanshutech** [meshery/meshery.io#1271]
#### Current State of the Meshery.io site

Currently the page https://meshery.io/community/ is empty

#### Desired State of the Meshery.io site

Need to implement the mockup for this page from [Figma design](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=16435%3A39494&mode=design&t=6qls5jOGn5gJKKgm-1)
Contributors can pick separate section to implement the page fast

- [ ] Section-1: Banner section

![image](https://github.com/meshery/meshery.io/assets/90546692/46923a6c-9dd4-408a-86d5-c35d1c3c3649)

- [ ] Section- 2: Resources section

![image](https://github.com/meshery/meshery.io/assets/90546692/02535164-abbb-479f-aa9f-35fa5d3fc238)

- [ ] Section-3: Handbook section

![image](https://github.com/meshery/meshery.io/assets/90546692/592b4e23-3205-45ae-b38d-24639c85a238)

- [ ] Section-4: Discuss forum section

![image](https://github.com/meshery/meshery.io/assets/90546692/ef3c7770-cf5e-45f3-8f2d-499307a955d9)

- [ ] Section-5: Meshmate section

![image](https://github.com/meshery/meshery.io/assets/90546692/3a3e97fb-8828-4773-98eb-838cbd795725)

- [ ] Section-6: Calendar section"

![image](https://github.com/meshery/meshery.io/assets/90546692/19762de4-5a3c-4c88-a165-08a01a8f36d9)

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by lanzkrish** [comment]
Hello Sudhanshu. Can I work on this?

**Comment by vishalvivekm** [comment]
> Hello Sudhanshu. Can I work on this?

Hi @lanzkrish 
Will you confirm if you've the site set up locally?
Also which sections out of 6 you want to work on ?

**Comment by lanzkrish** [comment]
No, I don't have the site set up locally yet.
I am a beginner so I can just work on the first 5 sections.

**Comment by lanzkrish** [comment]
I have set up the site locally.

**Comment by lanzkrish** [comment]
Yeh sure, That'll be great

**Comment by ayushsinha25** [comment]
Is there any social media I can connect to you on?

**Comment by lanzkrish** [comment]
> Is there any social media I can connect to you on?

go to my profile

**Comment by ranjanmangla1** [comment]
i would love to work on it

**Comment by Ykumar1415** [comment]
i would like to work on this issue please assign it to me ?

**Comment by AmanKumarVlgs** [comment]
Hey @vishalvivekm, I want to work on 

- Resource section
- Handlook section
- Meshmate section

Please assign me this task as I am familiar with the UI

**Comment by vishalvivekm** [comment]
Thanks @AmanKumarVlgs
Please name the section you want to start working on  @lanzkrish @ranjanmangla1 @Ykumar1415.
This is a high priority item so we want to see it off the finish line as quickly as we can.

**Comment by AmanKumarVlgs** [comment]
Hey @vishalvivekm, One question do we have to design a new figma or implement this UI in code?

**Comment by Gautam-666** [comment]
I want to get assigned to this issue.
I can work on the Banner section as no one wants it.

**Comment by ranjanmangla1** [comment]
@vishalvivekm i can work on : 
- banner
- meshmate
- calendar
- resources
- discuss

**Comment by lanzkrish** [comment]
I would like to work on the resources section

**Comment by lanzkrish** [comment]
> Thanks @AmanKumarVlgs Please name the section you want to start working on @lanzkrish @ranjanmangla1 @Ykumar1415. This is a high priority item so we want to see it off the finish line as quickly as we can.

I would like to work on the resources section

**Comment by deepchauhan2002** [comment]
Hey @vishalvivekm I would like to work on MeshMate section

**Comment by ayushsinha25** [comment]
@vishalvivekm please assign me the handbook section

**Comment by vishalvivekm** [comment]
@AmanKumarVlgs @deepchauhan2002 
Thanks for jumping into the effort, folks!
Please be sure to review the PRs which will be raised by the assignees and offer your feedback.
In case any of the assignee is unable to complete their task on time, this being an high priority issue, those sections will be reassigned.
In the meantime, I encourage you to explore the good first and help wanted issues within the Layer5 community

**Comment by sudhanshutech** [comment]
Anu updates or any help needed assigned folks

**Comment by Ykumar1415** [comment]
@sudhanshutech i have completed my task. only i need to give a finishing to it.

**Comment by lanzkrish** [comment]
Hey, I have created a pull request.
Waiting for feedback from you guys.
